const catalog={trending:[['Neon City','Cyber thriller','78%','#31245f','#c34274'],['Northbound','Drama','91%','#1f3d49','#a9774c'],['Afterlight','Sci-fi','96%','#111f48','#e65d71'],['The Signal','Mystery','89%','#2f263a','#d49c4d'],['Velocity','Action','84%','#152c34','#e84b39']],movies:[['Red Horizon','Action','94%','#4b1b1b','#e1a11e'],['Blue Hour','Romance','88%','#162d56','#9d6edb'],['Deep Space','Sci-fi','97%','#081e35','#49a8c8'],['Paper Hearts','Drama','86%','#522d42','#d89b80'],['Final Run','Thriller','92%','#201c1c','#a43b35']],series:[['Dark Matter','Sci-fi','95%','#151a35','#765bd6'],['The District','Crime','90%','#1e2931','#bc714a'],['Parallel','Mystery','93%','#2b1840','#53a9a2'],['Wildlands','Adventure','87%','#1e3b28','#b28c3b'],['Zero Hour','Thriller','91%','#282126','#dc5d6d']]};
const descriptions={};Object.values(catalog).flat().forEach(x=>descriptions[x[0]]=`${x[0]} is a ${x[1].toLowerCase()} story built around memorable characters, high-stakes choices and a cinematic world. This portfolio demo uses a handcrafted interface to recreate the feel of a modern streaming catalogue.`);
function render(id,items){document.getElementById(id).innerHTML=items.map(([title,genre,match,a,b])=>`<article class="card" data-title="${title}" data-genre="${genre}" style="--a:${a};--b:${b}"><div class="poster"><div class="badge">${match} Match</div><div class="poster-text"><small>${genre.toUpperCase()}</small><h3>${title}</h3></div></div></article>`).join('')}
render('trendingRow',catalog.trending);render('moviesRow',catalog.movies);render('seriesRow',catalog.series);
const modal=document.getElementById('modal');
function openModal(title){const item=Object.values(catalog).flat().find(x=>x[0]===title);if(!item)return;document.getElementById('modalTitle').textContent=title;document.getElementById('modalTag').textContent=item[1].toUpperCase();document.getElementById('modalMeta').textContent=`${item[2]} Match  •  2026  •  16+  •  2h 08m`;document.getElementById('modalDescription').textContent=descriptions[title];document.getElementById('modalPoster').style.background=`linear-gradient(120deg,${item[3]},${item[4]},#121212)`;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
document.addEventListener('click',e=>{const card=e.target.closest('.card');if(card)openModal(card.dataset.title);if(e.target.matches('[data-close]')){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}if(e.target.id==='infoHero')openModal('The Last Frontier');if(e.target.id==='playHero'||e.target.id==='modalPlay')alert('Demo mode: playback would start here.');if(e.target.matches('.view-all'))alert(`${e.target.dataset.section.charAt(0).toUpperCase()+e.target.dataset.section.slice(1)} catalogue expanded in the full product.`)});
document.getElementById('searchToggle').onclick=()=>document.getElementById('searchBox').classList.toggle('open');
document.getElementById('searchInput').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.card').forEach(c=>c.style.display=(!q||c.dataset.title.toLowerCase().includes(q)||c.dataset.genre.toLowerCase().includes(q))?'block':'none')});
window.addEventListener('scroll',()=>document.getElementById('navbar').classList.toggle('scrolled',scrollY>30));
