const albums=[
 ['Neon Dreams','The Midnight Club','#ec5b81','#34245d','N'],['After Hours','Nova Lane','#51306e','#161a39','A'],['City Lights','Violet Skies','#1e5260','#9b3f69','C'],['Golden Hour','Mira Sol','#d28c35','#4c2e47','G'],['Static Hearts','Low Frequency','#222','#9b5344','S'],['Open Roads','Northbound','#34634c','#c19b52','O'],['Parallel Lines','Echo Bloom','#334e79','#9a547e','P'],['Night Shift','The Signals','#1f2933','#9a3b42','N'],['Soft Focus','Luna Park','#b16b72','#302e58','F'],['Pulse','Afterimage','#21626c','#5b2d73','P']
];
const quick=[['Liked Songs','#3b286c','♥'],['Late Night Drive','#56302d','♫'],['Coding Mode','#1e4e48','⌘'],['Workout Energy','#7c3d25','⚡'],['Chill Sundays','#314b58','☼'],['Indie Finds','#4c3150','◆']];
function albumCard(a,i){return `<article class="album" data-title="${a[0]}" data-artist="${a[1]}"><div class="album-cover" style="--a:${a[2]};--b:${a[3]}">${a[4]}</div><h3>${a[0]}</h3><p>${a[1]}</p></article>`}
document.getElementById('quickGrid').innerHTML=quick.map(q=>`<div class="quick"><div class="quick-cover" style="background:${q[1]}">${q[2]}</div><span>${q[0]}</span></div>`).join('');
document.getElementById('madeForYou').innerHTML=albums.slice(0,5).map(albumCard).join('');document.getElementById('recently').innerHTML=albums.slice(5,10).map(albumCard).join('');document.getElementById('lateNight').innerHTML=albums.slice(2,7).map(albumCard).join('');
function selectTrack(title){const a=albums.find(x=>x[0]===title);if(!a)return;document.getElementById('playerTitle').textContent=a[0];document.getElementById('playerArtist').textContent=a[1];document.getElementById('playerCover').textContent=a[4];document.getElementById('playerCover').style.background=`linear-gradient(135deg,${a[2]},${a[3]})`;document.querySelectorAll('.album').forEach(x=>x.classList.toggle('highlight',x.dataset.title===title));}
document.addEventListener('click',e=>{const card=e.target.closest('.album');if(card)selectTrack(card.dataset.title);if(e.target.id==='playBtn'){e.target.textContent=e.target.textContent==='▶'?'Ⅱ':'▶'}if(e.target.id==='addPlaylist'){const name=prompt('Playlist name:');if(name){const a=document.createElement('a');a.href='#';a.textContent=name;document.getElementById('playlistList').appendChild(a)}}if(e.target.id==='mobileMenu')document.querySelector('.sidebar').style.display='flex'});
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.album').forEach(card=>{const ok=!q||card.dataset.title.toLowerCase().includes(q)||card.dataset.artist.toLowerCase().includes(q);card.style.display=ok?'block':'none'})});
document.getElementById('progress').addEventListener('input',e=>e.target.style.background=`linear-gradient(to right,#fff ${e.target.value}%,#555 ${e.target.value}%)`);
